export const events = [
  { image: "event-agentic.png", type: { en: "Virtual", ar: "افتراضي" }, date: "SEP 24, 2025", location: "", title: { en: "Agentic Automation: The Age of AI Twins", ar: "الأتمتة الوكالية: عصر التوائم الذكية الاصطناعية" } },
  { image: "event-chicago.png", type: { en: "In-Person", ar: "حضوري" }, date: "SEP 04, 2025", location: "CHICAGO, USA", title: { en: "NO-CODE DAY CHICAGO", ar: "فعالية الـ No-Code في شيكاغو" } },
  { image: "event-boston.png", type: { en: "In-Person", ar: "حضوري" }, date: "Sep 18, 2025", location: "Boston, USA", title: { en: "NO-CODE DAY BOSTON", ar: "فعالية الـ No-Code في بوسطن" } },
  { image: "event-italy.png", type: { en: "In-Person", ar: "حضوري" }, date: "Oct 09, 2025", location: "MONZA, ITALY", title: { en: "No-Code Day Italy", ar: "فعالية الـ No-Code في إيطاليا" } },
  { image: "event-london.png", type: { en: "In-Person", ar: "حضوري" }, date: "Oct 21, 2025", location: "London, UK", title: { en: "No-Code Day London", ar: "فعالية الـ No-Code في لندن" } },
  { image: "event-mexico.png", type: { en: "In-Person", ar: "حضوري" }, date: "Nov 25, 2025", location: "Mexico City, Mexico", title: { en: "NO-CODE DAY MEXICO", ar: "فعالية الـ No-Code في المكسيك" } },
];

export const news = [
  { image: "news-avidia.png", date: "SEPTEMBER 02, 2025", title: { en: "Avidia Bank Boosts Efficiency and Creates Unified Digital Future by Replacing Legacy CRM with Creatio", ar: "بنك أفيديا يعزز كفاءته ومستقبله الرقمي باستبدال نظام CRM القديم بمنصة كرياشو" }, summary: { en: "Massachusetts-based bank selects AI-native platform, boosting efficiency and building a foundation for future innovation with Agentic AI.", ar: "اختار البنك منصة مبنية على الذكاء الاصطناعي لرفع الكفاءة وبناء أساس للابتكار المستقبلي." } },
  { image: "news-appyzie.png", date: "AUGUST 20, 2025", title: { en: "Creatio and Appyzie Join Forces to Globally Accelerate AI-Powered Automation", ar: "كرياشو وآبيزي تتعاونان لتسريع الأتمتة بالذكاء الاصطناعي عالميًا" }, summary: { en: "New partnership helps organizations streamline CRM and operations with AI-native no-code platform and local delivery expertise.", ar: "شراكة تساعد المؤسسات على تبسيط إدارة العملاء والعمليات بمنصة دون كود وخبرات تنفيذ محلية." } },
  { image: "news-boston.png", date: "AUGUST 08, 2025", title: { en: "Creatio’s No-Code Days: The Age of AI Conference is Coming to Boston to Equip Enterprises for the AI Economy", ar: "فعاليات No-Code من كرياشو تصل إلى بوسطن لإعداد المؤسسات لاقتصاد الذكاء الاصطناعي" }, summary: { en: "No-Code Days series is heading to Boston September 18th, for a day of actionable learning, visionary insights on agentic automation and AI agents, and high-value networking opportunities for enterprise executives and technology leaders.", ar: "تتجه سلسلة فعاليات No-Code إلى بوسطن في 18 سبتمبر ليوم من التعلم العملي والرؤى حول الأتمتة الوكالية ووكلاء الذكاء الاصطناعي، وفرص للتواصل بين قادة المؤسسات والتقنية." } },
  { image: "news-gartner.png", date: "AUGUST 07, 2025", title: { en: "Creatio Recognized as a Visionary in the 2025 Gartner® Magic Quadrant™ for Sales Force Automation Platforms", ar: "تصنيف كرياشو ضمن الشركات ذات الرؤية في تقرير Gartner لعام 2025 لمنصات أتمتة المبيعات" }, summary: { en: "Creatio has been recognized for its Ability to Execute and Completeness of Vision.", ar: "حظيت كرياشو بالتقدير لقدرتها على التنفيذ واكتمال رؤيتها." } },
];
